New upstream version 3.2.0

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,6 @@
 language: python
 
 dist: xenial
-sudo: false
 
 services:
   - xvfb
@@ -22,8 +21,6 @@ addons:
     paths:
     - result_images.tar.bz2
   apt:
-    sources:
-      - sourceline: ppa:jonathonf/ffmpeg-3
     packages:
       - cm-super
       - dvipng
@@ -32,14 +29,15 @@ addons:
       - gir1.2-gtk-3.0
       - graphviz
       - inkscape
+      - lcov
       - libcairo2
       - libcairo2-dev
       - libffi-dev
       - libgeos-dev
       - libgirepository1.0-dev
       - lmodern
-      - otf-freefont
-      - pgf
+      - fonts-freefont-otf
+      - texlive-pictures
       - pkg-config
       - qtbase5-dev
       - texlive-fonts-recommended
@@ -57,22 +55,13 @@ env:
     - secure: RgJI7BBL8aX5FTOQe7xiXqWHMxWokd6GNUWp1NUV2mRLXPb9dI0RXqZt3UJwKTAzf1z/OtlHDmEkBoTVK81E9iUxK5npwyyjhJ8yTJmwfQtQF2n51Q1Ww9p+XSLORrOzZc7kAo6Kw6FIXN1pfctgYq2bQkrwJPRx/oPR8f6hcbY=
     - secure: E7OCdqhZ+PlwJcn+Hd6ns9TDJgEUXiUNEI0wu7xjxB2vBRRIKtZMbuaZjd+iKDqCKuVOJKu0ClBUYxmgmpLicTwi34CfTUYt6D4uhrU+8hBBOn1iiK51cl/aBvlUUrqaRLVhukNEBGZcyqAjXSA/Qsnp2iELEmAfOUa92ZYo1sk=
     - secure: dfjNqGKzQG5bu3FnDNwLG8H/C4QoieFo4PfFmZPdM2RY7WIzukwKFNT6kiDfOrpwt+2bR7FhzjOGlDECGtlGOtYPN8XuXGjhcP4a4IfakdbDfF+D3NPIpf5VlE6776k0VpvcZBTMYJKNFIMc7QPkOwjvNJ2aXyfe3hBuGlKJzQU=
-    # Variables controlling the build.
-    - MPLLOCALFREETYPE=1
-    # Variable for the location of an extra pip requirement file
-    - EXTRAREQS=
-    # Variable for the location of a pip version file
-    - PINNEDVERS=
+    - EXTRAREQS=  # Location of an extra pip requirements file.
+    - PINNEDVERS=  # Location of a pip constraints file.
     # Variables controlling the test run.
     - DELETE_FONT_CACHE=
     - NO_AT_BRIDGE=1  # Necessary for GTK3 interactive test.
-    # The number of processes is hardcoded, because using too many causes the
-    # Travis VM to run out of memory (since so many copies of inkscape and
-    # ghostscript are running at the same time).
-    - NPROC=2
     - OPENBLAS_NUM_THREADS=1
     - PYTHONFAULTHANDLER=1
-    - PYTEST_ADDOPTS="-raR --maxfail=50 --timeout=300 --durations=25 --cov-report= --cov=lib -n $NPROC --log-level=DEBUG"
     - RUN_PYTEST=1
     - RUN_FLAKE8=
 
@@ -90,7 +79,6 @@ matrix:
         - DELETE_FONT_CACHE=1
         - EXTRAREQS='-r requirements/testing/travis36.txt'
     - python: 3.7
-      sudo: true
     - python: "nightly"
       env:
         - PRE=--pre
@@ -110,22 +98,27 @@ matrix:
     - python: "nightly"
 
 before_install: |
-  # test with non-ascii in path
-  if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
+  case "$TRAVIS_OS_NAME" in
+  linux)
     export PATH=/usr/lib/ccache:$PATH
-  else
+    ;;
+  osx)
+    set -e
     ci/silence brew update
     brew uninstall numpy gdal postgis
+    brew unlink python@2
     brew upgrade python
-    brew install ffmpeg imagemagick mplayer ccache font-wenquanyi-zen-hei
+    brew install ffmpeg imagemagick mplayer ccache
     hash -r
     which python
     python --version
+    set +e
     # We could install ghostscript and inkscape here to test svg and pdf
     # but this makes the test time really long.
     # brew install ghostscript inkscape
     export PATH=/usr/local/opt/python/libexec/bin:/usr/local/opt/ccache/libexec:$PATH
-  fi
+    ;;
+  esac
 
 install:
   - |
@@ -137,6 +130,8 @@ install:
   - |
     # Install dependencies from PyPI.
     python -mpip install --upgrade $PRE -r requirements/testing/travis_all.txt $EXTRAREQS $PINNEDVERS
+  - |
+    # Install optional dependencies from PyPI.
     # GUI toolkits are pip-installable only for some versions of Python so
     # don't fail if we can't install them.  Make it easier to check whether the
     # install was successful by trying to import the toolkit (sometimes, the
@@ -158,9 +153,17 @@ install:
       echo 'wxPython is available' ||
       echo 'wxPython is not available'
 
+  # Set flag in a delayed manner to avoid issues with installing other packages
   - |
-    # Install matplotlib
-    python -mpip install -ve .
+    if [[ $TRAVIS_OS_NAME != 'osx' ]] && [[ $RUN_PYTEST == 1 ]]; then
+      export CPPFLAGS=--coverage
+    fi
+  - |
+    MPLLOCALFREETYPE=1 python -mpip install -ve .  # Install Matplotlib.
+  - |
+    if [[ $TRAVIS_OS_NAME != 'osx' ]] && [[ $RUN_PYTEST == 1 ]]; then
+      unset CPPFLAGS
+    fi
 
 before_script: |
   if [[ $DELETE_FONT_CACHE == 1 ]]; then
@@ -168,18 +171,19 @@ before_script: |
   fi
 
 script:
-  # each script we want to run need to go in it's own section and the program you want
-  # to fail travis need to be the last thing called
+  # Each script we want to run need to go in its own section and the program
+  # you want to fail travis needs to be the last thing called.
   - |
     if [[ $RUN_PYTEST == 1 ]]; then
-      echo "Calling pytest with the following arguments: $PYTEST_ADDOPTS"
-      python -mpytest
+      # The number of processes is hardcoded (-n2), because using too many
+      # causes the Travis VM to run out of memory (since so many copies of
+      # inkscape and ghostscript are running at the same time).
+      python -mpytest -raR --maxfail=50 --timeout=300 --durations=25 --cov-report= --cov=lib -n2 --log-level=DEBUG
     fi
   - |
     if [[ $RUN_FLAKE8 == 1 ]]; then
       flake8 --statistics && echo "Flake8 passed without any issues!"
     fi
-
 
 before_cache: |
   rm -rf $HOME/.cache/matplotlib/tex.cache
@@ -193,5 +197,9 @@ after_failure: |
     echo "The result images will only be uploaded if they are on the matplotlib/matplotlib repo - this is for security reasons to prevent arbitrary PRs echoing security details."
   fi
 
-after_success: |
-  codecov -e TRAVIS_PYTHON_VERSION
+after_success:
+  - lcov --capture --directory . --output-file coverage.info
+  - lcov --remove coverage.info --output-file coverage.info '/usr/*' '/home/travis/build/matplotlib/matplotlib/build/*' '/home/travis/build/matplotlib/matplotlib/extern/*' # filter system-files
+  - lcov --list coverage.info
+  # Uploading to CodeCov but excluding gcov reports
+  - bash <(curl -s https://codecov.io/bash) -f "!*.gcov" -X gcov -e TRAVIS_PYTHON_VERSION|| echo "Codecov did not collect coverage reports"
